// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWeTttSq3QF6OhQY1X-lXCZYTSMW0SU68',
    appId: '1:156994713450:web:6d2877a056266532f65713',
    messagingSenderId: '156994713450',
    projectId: 'kronosbysphinx',
    authDomain: 'kronosbysphinx.firebaseapp.com',
    storageBucket: 'kronosbysphinx.appspot.com',
    measurementId: 'G-N0NYD1079V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhF5BEMSadojIjN9dyyCV3sZe3bnIt4I',
    appId: '1:156994713450:android:22146f7e15c8d256f65713',
    messagingSenderId: '156994713450',
    projectId: 'kronosbysphinx',
    storageBucket: 'kronosbysphinx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPwBdUSpfFN--4TuV7SPOwUOLMO2AxKw',
    appId: '1:156994713450:ios:47853dfc9fb4a541f65713',
    messagingSenderId: '156994713450',
    projectId: 'kronosbysphinx',
    storageBucket: 'kronosbysphinx.appspot.com',
    iosBundleId: 'com.example.kronosSoftware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWeTttSq3QF6OhQY1X-lXCZYTSMW0SU68',
    appId: '1:156994713450:web:f6d784fba91f2777f65713',
    messagingSenderId: '156994713450',
    projectId: 'kronosbysphinx',
    authDomain: 'kronosbysphinx.firebaseapp.com',
    storageBucket: 'kronosbysphinx.appspot.com',
    measurementId: 'G-NWK498JJNJ',
  );
}
